project:
  type: website
  output-dir: docs

website:
  title: "greg-mck"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - pubs.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual

